### ISSUE TITLE
Installation Problem under openSUSE 13.1

### ISSUE THREAD

**Issue by pschmitt27** [suvit/suds-passworddigest#5]
After entering

 pip install suds-passworddigest

I obtain the following error message:

Downloading/unpacking suds-passworddigest
  Downloading suds_passworddigest-0.1.2.zip
  Running setup.py egg_info for package suds-passworddigest
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_pschmitt/suds-passworddigest/setup.py", line 18, in <module>
        long_description=file(
    NameError: name 'file' is not defined
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_pschmitt/suds-passworddigest/setup.py", line 18, in <module>

```
long_description=file(
```

NameError: name 'file' is not defined

What is going wrong here?

**Comment by pschmitt27** [comment]
Using   pip-2.7   as superuser succeeded.
