### ISSUE TITLE
pipenv install error > NameError: name 'file' is not defined

### ISSUE THREAD

**Issue by kgbeast** [suvit/suds-passworddigest#6]
(pyCam) [johnb@centos7-64 pyCam]$ pipenv  install suds-passworddigest
Installing suds-passworddigest…
Error:  An error occurred while installing suds-passworddigest!
Error text: Collecting suds-passworddigest
  Downloading suds_passworddigest-0.1.2.zip (5.6 kB)

    ERROR: Command errored out with exit status 1:
     command: /home/johnb/.local/share/virtualenvs/pyCam-6-L3NT8f/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-czxuh2nu/suds-passworddigest/setup.py'"'"'; __file__='"'"'/tmp/pip-install-czxuh2nu/suds-passworddigest/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mdny780p
         cwd: /tmp/pip-install-czxuh2nu/suds-passworddigest/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-czxuh2nu/suds-passworddigest/setup.py", line 18, in <module>
        long_description=file(
    NameError: name 'file' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

This is likely caused by a bug in suds-passworddigest. Report this to its maintainers.
✘ Installation Failed

**Comment by Kokerboom** [comment]
I have the same issue.

**Comment by zobbo** [comment]
It'a python 2 only. Use https://github.com/kamachok/suds-passworddigest-py3
